import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';

// Load environment variables from .env.local
dotenv.config({ path: '.env' });


const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const supabase = createClient(supabaseUrl, supabaseKey);

const projects = [
  {
    project_name: "Solana (Lab Core)",
    github_repo_url: "https://github.com/solana-labs/solana",
    category: "Core infrastructure / Node",
    primary_language: "Rust",
    stars: 13900,
    last_updated: "19 days ago",
    license: "Apache-2.0",
    maintainer: "Solana Labs",
    active: "N",
    brief_description: "Web-Scale Blockchain for fast secure scalable apps",
    notes: "Archived but reference point",
  },
  {
    project_name: "Anchor",
    github_repo_url: "https://github.com/coral-xyz/anchor",
    category: "Developer Framework",
    primary_language: "Rust",
    stars: 3300,
    last_updated: "17 hours ago",
    license: "MIT/Apache-2.0",
    maintainer: "Coral",
    active: "Y",
    brief_description: "Solana Sealevel Framework",
    notes: "Great for smart-contract development",
  },
  {
    project_name: "Solana Program Library",
    github_repo_url: "https://github.com/solana-labs/solana-program-library",
    category: "On-chain Standard Programs",
    primary_language: "Rust",
    stars: 3100,
    last_updated: "1 hour ago",
    license: "Apache-2.0",
    maintainer: "Solana Labs",
    active: "Y",
    brief_description: "Programs for tokens/governance",
    notes: "Used widely in DeFi/NFT",
  },
  {
    project_name: "Solana Web3.js",
    github_repo_url: "https://github.com/solana-labs/solana-web3.js",
    category: "Client SDK",
    primary_language: "TypeScript",
    stars: 1900,
    last_updated: "11 hours ago",
    license: "MIT",
    maintainer: "Solana Labs",
    active: "Y",
    brief_description: "JavaScript SDK for Solana",
    notes: "Must-have for front-end",
  },
  {
    project_name: "Wallet Adapter",
    github_repo_url: "https://github.com/anza-xyz/wallet-adapter",
    category: "Wallet Integration",
    primary_language: "TypeScript",
    stars: 1700,
    last_updated: "3 days ago",
    license: "MIT",
    maintainer: "Anza XYZ / Solana Labs",
    active: "Y",
    brief_description: "Modular wallet components",
    notes: "Browser wallet support",
  },
  {
    project_name: "Solana Labs/Token List",
    github_repo_url: "https://github.com/solana-labs/token-list",
    category: "Token Registry",
    primary_language: "Go",
    stars: 1500,
    last_updated: "Jul 24 2024",
    license: "MIT",
    maintainer: "Solana Labs",
    active: "Y",
    brief_description: "Community token registry",
    notes: "",
  },
  {
    project_name: "Anza XYZ/Solana Pay",
    github_repo_url: "https://github.com/anza-xyz/solana-pay",
    category: "Payments / On-chain Payments",
    primary_language: "TypeScript",
    stars: 1400,
    last_updated: "Nov 7 2024",
    license: "MIT",
    maintainer: "Anza XYZ",
    active: "Y",
    brief_description: "Decentralized payment standard",
    notes: "",
  },
  {
    project_name: "Solang",
    github_repo_url: "https://github.com/hyperledger/solang",
    category: "Compiler",
    primary_language: "Rust",
    stars: 1200,
    last_updated: "yesterday",
    license: "Apache-2.0",
    maintainer: "Hyperledger",
    active: "Y",
    brief_description: "Solidity compiler for Solana & Polkadot",
    notes: "",
  },
  {
    project_name: "Solana Py",
    github_repo_url: "https://github.com/michaelhly/solana-py",
    category: "Client SDK",
    primary_language: "Python",
    stars: 1200,
    last_updated: "2 days ago",
    license: "MIT",
    maintainer: "Michaelhly",
    active: "Y",
    brief_description: "Python SDK for Solana",
    notes: "",
  },
  {
    project_name: "Learn Web3 Dapp",
    github_repo_url: "https://github.com/figment-networks/learn-web3-dapp",
    category: "Learning Tool",
    primary_language: "TypeScript",
    stars: 1200,
    last_updated: "Mar 2 2025",
    license: "MIT",
    maintainer: "Figment Networks",
    active: "Y",
    brief_description: "Next.js app for Web3 learning",
    notes: "",
  },
  {
    project_name: "Solana Pay",
    github_repo_url: "https://github.com/solana-labs/solana-pay",
    category: "Payments / On-chain Payments",
    primary_language: "TypeScript",
    stars: 1200,
    last_updated: "17 days ago",
    license: "MIT",
    maintainer: "Solana Labs",
    active: "Y",
    brief_description: "Solana payment standard",
    notes: "",
  },
  {
    project_name: "Solana Trading Bot",
    github_repo_url: "https://github.com/warp-id/solana-trading-bot",
    category: "Trading Automation",
    primary_language: "TypeScript",
    stars: 1100,
    last_updated: "yesterday",
    license: "MIT",
    maintainer: "Warp-ID",
    active: "Y",
    brief_description: "Beta trading bot",
    notes: "",
  },
  {
    project_name: "Solana Worken SDK PHP",
    github_repo_url: "https://github.com/paidworkco/solana-worken-sdk-php",
    category: "Client SDK",
    primary_language: "PHP",
    stars: 928,
    last_updated: "2 hours ago",
    license: "MIT",
    maintainer: "Paidworkco",
    active: "Y",
    brief_description: "PHP SDK for Solana",
    notes: "",
  },
  {
    project_name: "Example Helloworld",
    github_repo_url: "https://github.com/solana-labs/example-helloworld",
    category: "Learning / Example",
    primary_language: "TypeScript",
    stars: 871,
    last_updated: "Mar 4 2025",
    license: "MIT",
    maintainer: "Solana Labs",
    active: "Y",
    brief_description: "Hello world example program",
    notes: "",
  },
  {
    project_name: "Ant Design Web3",
    github_repo_url: "https://github.com/ant-design/ant-design-web3",
    category: "UI Components",
    primary_language: "TypeScript",
    stars: 731,
    last_updated: "49 minutes ago",
    license: "MIT",
    maintainer: "Ant Design",
    active: "Y",
    brief_description: "Web3 React UI components",
    notes: "",
  },
  {
    project_name: "Smart Contract Security Audits",
    github_repo_url:
      "https://github.com/softstackHQ/Smart-Contract-Security-Audits",
    category: "Security Resource",
    primary_language: "HTML",
    stars: 726,
    last_updated: "7 days ago",
    license: "MIT",
    maintainer: "SoftstackHQ",
    active: "Y",
    brief_description: "Audit resources for smart contracts",
    notes: "",
  },
  {
    project_name: "Firedancer",
    github_repo_url: "https://github.com/firedancer-io/firedancer",
    category: "Consensus Node",
    primary_language: "C",
    stars: 725,
    last_updated: "30 minutes ago",
    license: "Apache-2.0",
    maintainer: "Jump Crypto",
    active: "Y",
    brief_description: "High-performance Solana consensus node",
    notes: "",
  },
  {
    project_name: "Solana Go",
    github_repo_url: "https://github.com/gagliardetto/solana-go",
    category: "Client SDK",
    primary_language: "Go",
    stars: 671,
    last_updated: "13 days ago",
    license: "MIT",
    maintainer: "Gagliardetto",
    active: "Y",
    brief_description: "Go SDK & RPC client",
    notes: "",
  },
  {
    project_name: "Audius Protocol",
    github_repo_url: "https://github.com/AudiusProject/audius-protocol",
    category: "Media / Streaming",
    primary_language: "TypeScript",
    stars: 545,
    last_updated: "8 hours ago",
    license: "MIT",
    maintainer: "Audius Project",
    active: "Y",
    brief_description: "Decentralized audio protocol",
    notes: "",
  },
  {
    project_name: "Cake Wallet",
    github_repo_url: "https://github.com/cake-tech/cake_wallet",
    category: "Wallet",
    primary_language: "Dart",
    stars: 544,
    last_updated: "12 seconds ago",
    license: "MIT",
    maintainer: "Cake-Tech",
    active: "Y",
    brief_description: "Non-custodial multi-currency wallet",
    notes: "",
  },
  {
    project_name: "Awesome MEV",
    github_repo_url: "https://github.com/0xemperor/Awesome-MEV",
    category: "Research Resource",
    primary_language: "Markdown",
    stars: 514,
    last_updated: "Sep 2 2023",
    license: "MIT",
    maintainer: "0xEmperor",
    active: "Y",
    brief_description: "MEV research list",
    notes: "",
  },
  {
    project_name: "Complete Guide to Full Stack Solana Dev",
    github_repo_url:
      "https://github.com/dabit3/complete-guide-to-full-stack-solana-development",
    category: "Tutorial",
    primary_language: "JavaScript",
    stars: 474,
    last_updated: "Jul 12 2023",
    license: "MIT",
    maintainer: "Dabit3",
    active: "Y",
    brief_description: "Full-stack dev guide for Solana",
    notes: "",
  },
  {
    project_name: "Solsec",
    github_repo_url: "https://github.com/0xsanny/solsec",
    category: "Security Resource",
    primary_language: "Markdown",
    stars: 463,
    last_updated: "9 days ago",
    license: "MIT",
    maintainer: "0xsanny",
    active: "Y",
    brief_description: "Solana security learning",
    notes: "",
  },
  {
    project_name: "Sealevel Attacks",
    github_repo_url: "https://github.com/coral-xyz/sealevel-attacks",
    category: "Security Resource",
    primary_language: "Rust",
    stars: 457,
    last_updated: "Mar 20 2025",
    license: "MIT",
    maintainer: "Coral",
    active: "Y",
    brief_description: "Common Solana exploits & protections",
    notes: "",
  },
  {
    project_name: "Solana Jupiter Bot",
    github_repo_url: "https://github.com/ARBProtocol/solana-jupiter-bot",
    category: "Trading Automation",
    primary_language: "JavaScript",
    stars: 453,
    last_updated: "Feb 14 2025",
    license: "MIT",
    maintainer: "ARBProtocol",
    active: "Y",
    brief_description: "Arbitrage bot using Jupiter",
    notes: "",
  },
  {
    project_name: "Program Examples",
    github_repo_url: "https://github.com/solana-developers/program-examples",
    category: "Learning / Examples",
    primary_language: "TypeScript",
    stars: 413,
    last_updated: "3 days ago",
    license: "MIT",
    maintainer: "Solana Developers",
    active: "Y",
    brief_description: "Collection of example programs",
    notes: "",
  },
  {
    project_name: "Solana Playground",
    github_repo_url: "https://github.com/solana-playground/solana-playground",
    category: "Developer Tool",
    primary_language: "Rust",
    stars: 399,
    last_updated: "6 hours ago",
    license: "MIT",
    maintainer: "Solana Playground",
    active: "Y",
    brief_description: "Browser-based dev environment",
    notes: "",
  },
  {
    project_name: "Moralis JS SDK",
    github_repo_url: "https://github.com/MoralisWeb3/Moralis-JS-SDK",
    category: "Client SDK",
    primary_language: "TypeScript",
    stars: 361,
    last_updated: "3 days ago",
    license: "MIT",
    maintainer: "MoralisWeb3",
    active: "Y",
    brief_description: "Javascript SDK",
    notes: "",
  },
  {
    project_name: "Solana Developer Resources",
    github_repo_url:
      "https://github.com/CristinaSolana/solana-developer-resources",
    category: "Learning Resources",
    primary_language: "Markdown",
    stars: 351,
    last_updated: "Jan 29 2025",
    license: "MIT",
    maintainer: "CristinaSolana",
    active: "Y",
    brief_description: "Dev resource list",
    notes: "",
  },
  {
    project_name: "Metaplex JS SDK",
    github_repo_url: "https://github.com/metaplex-foundation/js",
    category: "Client SDK",
    primary_language: "TypeScript",
    stars: 349,
    last_updated: "Mar 5 2025",
    license: "MIT",
    maintainer: "Metaplex Foundation",
    active: "Y",
    brief_description: "JS SDK for Metaplex programs",
    notes: "",
  },
  {
    project_name: "Tatum JS SDK",
    github_repo_url: "https://github.com/tatumio/tatum-js",
    category: "Client SDK",
    primary_language: "TypeScript",
    stars: 348,
    last_updated: "yesterday",
    license: "MIT",
    maintainer: "Tatumio",
    active: "Y",
    brief_description: "Full-featured blockchain SDK",
    notes: "",
  },
  {
    project_name: "Create Dapp Solana Nextjs",
    github_repo_url: "https://github.com/thuglabs/create-dapp-solana-nextjs",
    category: "Boilerplate",
    primary_language: "TypeScript",
    stars: 345,
    last_updated: "Mar 6 2023",
    license: "MIT",
    maintainer: "ThugLabs",
    active: "Y",
    brief_description: "Solana + Next.js boilerplate",
    notes: "",
  },
  {
    project_name: "Gem Farm",
    github_repo_url: "https://github.com/gemworks/gem-farm",
    category: "NFT Utility",
    primary_language: "TypeScript",
    stars: 333,
    last_updated: "Dec 28 2023",
    license: "MIT",
    maintainer: "Gemworks",
    active: "Y",
    brief_description: "NFT staking utility",
    notes: "",
  },
  {
    project_name: "Motionia",
    github_repo_url: "https://github.com/abhiprojectz/motionia",
    category: "Animation Tool",
    primary_language: "Python",
    stars: 324,
    last_updated: "Mar 5 2025",
    license: "MIT",
    maintainer: "Abhiprojectz",
    active: "Y",
    brief_description: "Smart JS animation library",
    notes: "",
  },
  {
    project_name: "Solana Onboarding",
    github_repo_url: "https://github.com/ilmoi/solana-onboarding",
    category: "Learning",
    primary_language: "Markdown",
    stars: 313,
    last_updated: "Sep 28 2021",
    license: "MIT",
    maintainer: "Ilmoi",
    active: "N",
    brief_description: "Onboarding checklist for Solana",
    notes: "Stale",
  },
  {
    project_name: "Quill Audit Reports",
    github_repo_url: "https://github.com/Quillhash/QuillAudit_Reports",
    category: "Security Resource",
    primary_language: "Markdown",
    stars: 301,
    last_updated: "20 hours ago",
    license: "MIT",
    maintainer: "Quillhash",
    active: "Y",
    brief_description: "Audit reports for DeFi/NFTs",
    notes: "",
  },
  {
    project_name: "Awesome Solana",
    github_repo_url: "https://github.com/paul-schaaf/awesome-solana",
    category: "Resource List",
    primary_language: "Markdown",
    stars: 297,
    last_updated: "Nov 25 2022",
    license: "MIT",
    maintainer: "Paul-Schaaf",
    active: "Y",
    brief_description: "Curated Solana resources list",
    notes: "",
  },
  {
    project_name: "Unidata",
    github_repo_url: "https://github.com/NaturalSelectionLabs/Unidata",
    category: "Data Utility",
    primary_language: "TypeScript",
    stars: 283,
    last_updated: "May 18 2025",
    license: "MIT",
    maintainer: "NaturalSelectionLabs",
    active: "Y",
    brief_description: "Human-friendly Web3 data access",
    notes: "",
  },
  {
    project_name: "Solana Escrow",
    github_repo_url: "https://github.com/paul-schaaf/solana-escrow",
    category: "Example/Guide",
    primary_language: "TypeScript",
    stars: 282,
    last_updated: "Jul 2 2022",
    license: "MIT",
    maintainer: "Paul-Schaaf",
    active: "Y",
    brief_description: "Escrow reference implementation",
    notes: "",
  },
  {
    project_name: "Solana BPF Program Template",
    github_repo_url: "https://github.com/mvines/solana-bpf-program-template",
    category: "Boilerplate",
    primary_language: "Rust",
    stars: 279,
    last_updated: "Jun 20 2025",
    license: "MIT",
    maintainer: "Mvines",
    active: "Y",
    brief_description: "BPF program skeleton",
    notes: "",
  },
  {
    project_name: "Treat Toolbox",
    github_repo_url: "https://github.com/theskeletoncrew/treat-toolbox",
    category: "NFT Utility",
    primary_language: "TypeScript",
    stars: 277,
    last_updated: "Apr 25 2022",
    license: "MIT",
    maintainer: "The Skeleton Crew",
    active: "Y",
    brief_description: "Generative NFT utility",
    notes: "",
  },
  {
    project_name: "Coin Space",
    github_repo_url: "https://github.com/CoinSpace/CoinSpace",
    category: "Wallet/Utility",
    primary_language: "JavaScript",
    stars: 275,
    last_updated: "22 hours ago",
    license: "MIT",
    maintainer: "CoinSpace",
    active: "Y",
    brief_description: "Crypto wallet",
    notes: "",
  },
  {
    project_name: "Unity Solana Wallet",
    github_repo_url: "https://github.com/allartprotocol/unity-solana-wallet",
    category: "Wallet",
    primary_language: "C#",
    stars: 270,
    last_updated: "Jun 1 2022",
    license: "MIT",
    maintainer: "AllArtProtocol",
    active: "Y",
    brief_description: "Unity-based wallet",
    notes: "",
  },
  {
    project_name: "Jupiter SDK (jup-ag)",
    github_repo_url: "https://github.com/jup-ag",
    category: "DEX Aggregator / SDK Layer",
    primary_language: "TypeScript/Rust",
    stars: 284,
    last_updated: "Aug 19 2025",
    license: "Varies",
    maintainer: "jup-ag",
    active: "Y",
    brief_description: "Tools powering Jupiter routing and integrations",
    notes: "",
  },
  {
    project_name: "Raydium SDK-V2",
    github_repo_url: "https://github.com/raydium-io/raydium-sdk-V2",
    category: "DeFi SDK",
    primary_language: "TypeScript",
    stars: 311,
    last_updated: "Aug 18 2025",
    license: "GPL-3.0",
    maintainer: "Raydium Labs",
    active: "Y",
    brief_description: "Raydium TypeScript SDK for integration",
    notes: "",
  },
  {
    project_name: "Raydium CLMM",
    github_repo_url: "https://github.com/raydium-io/raydium-clmm",
    category: "AMM / Liquidity Engine",
    primary_language: "Rust",
    stars: 266,
    last_updated: "Jul 29 2025",
    license: "Apache-2.0",
    maintainer: "Raydium Labs",
    active: "Y",
    brief_description: "Concentrated liquidity engine",
    notes: "",
  },
  {
    project_name: "Drift Protocol v2",
    github_repo_url: "https://github.com/drift-labs/protocol-v2",
    category: "Perpetuals DEX",
    primary_language: "Rust/TypeScript",
    stars: 302,
    last_updated: "Aug 13 2025",
    license: "Apache-2.0",
    maintainer: "Drift Labs",
    active: "Y",
    brief_description: "On-chain perpetuals DEX with SDK support",
    notes: "",
  },
  {
    project_name: "Jupiter Python SDK",
    github_repo_url: "https://github.com/0xTaoDev/jupiter-python-sdk",
    category: "SDK / Tooling",
    primary_language: "Python",
    stars: 240,
    last_updated: "",
    license: "MIT",
    maintainer: "0xTaoDev",
    active: "Y",
    brief_description: "Python interface for Jupiter features",
    notes: "",
  },
  {
    project_name: "Drift JIT Proxy",
    github_repo_url: "https://github.com/drift-labs/jit-proxy",
    category: "Liquidity Infrastructure",
    primary_language: "Rust/TypeScript",
    stars: 49,
    last_updated: "Jul 28 2025",
    license: "Apache-2.0",
    maintainer: "Drift Labs",
    active: "Y",
    brief_description: "JIT liquidity proxy for Drift v2",
    notes: "",
  },
  {
    project_name: "Solana Swap Tutorial",
    github_repo_url: "https://github.com/builderby/solana-swap-tutorial",
    category: "Developer Tutorial",
    primary_language: "JavaScript/TypeScript",
    stars: 0,
    last_updated: " ",
    license: "MIT",
    maintainer: "builderby",
    active: "Y",
    brief_description: "Guide to swaps using Jupiter V6 & Jito",
    notes: "",
  },
  {
    project_name: "Create-Solana-Dapp",
    github_repo_url: "https://github.com/solana-developers/create-solana-dapp",
    category: "Dev Tooling",
    primary_language: "JavaScript/TypeScript",
    stars: 0,
    last_updated: "2025",
    license: "MIT",
    maintainer: "Solana Developers",
    active: "Y",
    brief_description: "Boilerplate for Solana dApps",
    notes: "",
  },
  {
    project_name: "Solana Project Template",
    github_repo_url:
      "https://github.com/metaplex-foundation/solana-project-template",
    category: "Dev Tooling",
    primary_language: "JavaScript/TypeScript",
    stars: 0,
    last_updated: "2025",
    license: "MIT",
    maintainer: "Metaplex",
    active: "Y",
    brief_description: "Starter template for new Solana projects",
    notes: "",
  },
  {
    project_name: "Zircon",
    github_repo_url: "https://github.com/joeymeere/zircon",
    category: "Dev Tooling",
    primary_language: "Rust",
    stars: 0,
    last_updated: "No update",
    license: "MIT",
    maintainer: "Joey Meere",
    active: "N",
    brief_description: "Solana toolkit by Joey Meere",
    notes: "",
  },
  {
    project_name: "SOLfees.fyi",
    github_repo_url: "https://github.com/ronnyhaase/solfees.fyi",
    category: "Dev Tooling",
    primary_language: "JavaScript",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Ronny Haase",
    active: "Y",
    brief_description: "Fee tracker for Solana transactions",
    notes: "",
  },
  {
    project_name: "Solathon",
    github_repo_url: "https://github.com/SuperteamDAO/solathon",
    category: "Dev Tooling",
    primary_language: "",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "SuperteamDAO",
    active: "Y",
    brief_description: "Hacktober style toolkit by SuperteamDAO",
    notes: "",
  },
  {
    project_name: "Explorer Kit",
    github_repo_url: "https://github.com/solana-fm/explorer-kit",
    category: "Dev Tooling",
    primary_language: "JavaScript",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "SolanaFM",
    active: "Y",
    brief_description: "Explorer front-end templates",
    notes: "",
  },
  {
    project_name: "Soda",
    github_repo_url: "https://github.com/Web3-Builders-Alliance/soda",
    category: "Dev Tooling",
    primary_language: "JavaScript",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Web3 Builders Alliance",
    active: "Y",
    brief_description: "Web3 UI components",
    notes: "",
  },
  {
    project_name: "Squads CLI",
    github_repo_url: "https://github.com/Squads-Protocol/squads-cli",
    category: "Dev Tooling",
    primary_language: "JavaScript",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Squads Protocol",
    active: "Y",
    brief_description: "DAO multisig CLI",
    notes: "",
  },
  {
    project_name: "Blockbuster",
    github_repo_url: "https://github.com/metaplex-foundation/blockbuster",
    category: "Infrastructure",
    primary_language: "",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Metaplex",
    active: "Y",
    brief_description: "Media management framework",
    notes: "",
  },
  {
    project_name: "Openbook v2",
    github_repo_url: "https://github.com/openbook-dex/openbook-v2",
    category: "DeFi",
    primary_language: "Dex",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Openbook",
    active: "Y",
    brief_description: "Orderbook DEX on Solana",
    notes: "",
  },
  {
    project_name: "Mango v4",
    github_repo_url: "https://github.com/blockworks-foundation/mango-v4",
    category: "DeFi",
    primary_language: "Derivatives",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Mango Markets",
    active: "Y",
    brief_description: "Perpetuals/derivatives",
    notes: "",
  },
  {
    project_name: "Whirlpools",
    github_repo_url: "https://github.com/orca-so/whirlpools",
    category: "DeFi",
    primary_language: "AMM",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Orca",
    active: "Y",
    brief_description: "Concentrated liquidity pools",
    notes: "",
  },
  {
    project_name: "Elusiv",
    github_repo_url: "https://github.com/elusiv-privacy/elusiv",
    category: "Infrastructure",
    primary_language: "Privacy",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Elusiv",
    active: "Y",
    brief_description: "Privacy payments on Solana",
    notes: "",
  },
  {
    project_name: "Jito Relayer",
    github_repo_url: "https://github.com/jito-foundation/jito-relayer",
    category: "Infrastructure",
    primary_language: "Bot",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Jito Labs",
    active: "Y",
    brief_description: "MEV relayer infrastructure",
    notes: "",
  },
  {
    project_name: "Lite RPC",
    github_repo_url: "https://github.com/blockworks-foundation/lite-rpc",
    category: "Infrastructure",
    primary_language: "RPC",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Blockworks",
    active: "Y",
    brief_description: "Lightweight RPC endpoint",
    notes: "",
  },
  {
    project_name: "Xray",
    github_repo_url: "https://github.com/helius-labs/xray",
    category: "Data Tooling",
    primary_language: "",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Helius Labs",
    active: "Y",
    brief_description: "Blockchain data explorer",
    notes: "",
  },
  {
    project_name: "SOL CLI Explorer",
    github_repo_url: "https://github.com/cavemanloverboy/sol",
    category: "Data Tooling",
    primary_language: "CLI",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "cavemanloverboy",
    active: "Y",
    brief_description: "Command-line chain explorer",
    notes: "",
  },
  {
    project_name: "Ore v1",
    github_repo_url: "https://github.com/regolith-labs/ore",
    category: "Misc",
    primary_language: "Token Launch",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Regolith Labs",
    active: "Y",
    brief_description: "Token deployment tools",
    notes: "",
  },
  {
    project_name: "PubKey Link",
    github_repo_url: "https://github.com/pubkeyapp/pubkey-link",
    category: "Misc",
    primary_language: "Social",
    stars: 0,
    last_updated: "Yes",
    license: "MIT",
    maintainer: "Beeman",
    active: "Y",
    brief_description: "On-chain profile linking tools",
    notes: "",
  },
];

async function seed() {
  for (const project of projects) {
    const { error } = await supabase.from("projects").insert({
      project_name: project.project_name,
      github_repo_url: project.github_repo_url,
      category: project.category,
      primary_language: project.primary_language,
      stars: project.stars,
      last_updated: project.last_updated,
      license: project.license,
      maintainer: project.maintainer,
      active: project.active,
      brief_description: project.brief_description,
      notes: project.notes,
    });
    if (error) console.error("Error inserting:", error);
  }
  console.log("Seeding complete!");
}

seed();
